#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
J=${JJ_BIN:-"$ROOT/.toolchain/bin/jj"}
OUT=${1:-"$ROOT/research/command-inventory.md"}
VERSION=$("$J" version | awk '{print $2}')
SNAP=${2:-"$ROOT/research/cli-help-$VERSION.txt"}
[[ -x "$J" ]] || { echo "jj binary not executable: $J" >&2; exit 2; }
mkdir -p "$(dirname "$OUT")"
help_for() { "$J" --no-pager help "$@" 2>&1; }
commands_from() {
  awk '
    /^Commands:/ { in_commands=1; next }
    in_commands && /^Options:/ { in_commands=0 }
    in_commands && /^[[:space:]]{2}[a-z][a-z0-9-]*[[:space:]]/ { print $1 }
  '
}
declare -a queue=("")
declare -A seen=()
printf 'jj %s\nGenerated by scripts/inventory-cli.sh\n' "$VERSION" > "$SNAP"
while ((${#queue[@]})); do
  path=${queue[0]}; queue=("${queue[@]:1}")
  key=${path:-__root__}
  [[ ${seen[$key]+yes} ]] && continue
  seen[$key]=1
  if [[ -n "$path" ]]; then read -r -a argv <<< "$path"; else argv=(); fi
  out=$(help_for "${argv[@]}")
  { printf '\n===== jj help %s =====\n\n' "$path"; printf '%s\n' "$out"; } >> "$SNAP"
  while read -r child; do
    [[ -z "$child" ]] && continue
    if [[ -n "$path" ]]; then queue+=("$path $child"); else queue+=("$child"); fi
  done < <(printf '%s\n' "$out" | commands_from)
done
{
  printf '# Command inventory — jj %s\n\n' "$VERSION"
  printf 'Generated from %s on %s UTC. Raw help is in %s.\n\n' "$J" "$(date -u +%F)" "$(basename "$SNAP")"
  printf '| Command path | Dedicated help captured |\n|---|---|\n'
  while IFS= read -r line; do
    [[ $line == '===== jj help '* ]] || continue
    path=${line#===== jj help }; path=${path% =====}
    [[ -n "$path" ]] && printf '| jj %s | yes |\n' "$path"
  done < "$SNAP"
  printf '\n## Captured command paths\n\n'
  printf '%s\n' "$(grep -c '^| jj ' "$OUT" 2>/dev/null || true) command paths (including nested paths)."
} > "$OUT"
for topic in revsets filesets templates config glossary; do
  help_for -k "$topic" > "$ROOT/research/help-$topic-$VERSION.md"
done
echo "wrote $OUT and $SNAP" >&2
